// EXPECTED_RESULT: "exception with a clear message"
log("this is unexpected")
