// Expected: runtime error
module errorTrace02
def rootError() {
    rep(x <- 1) {
        foldMin(NEGATIVE_INFINITY, 
            nbr(
                sin("I'm definitely not a number.")
            )
        )
    }
}
def aCall() {
    nbr(rootError())
}
def anotherCall() {
    /*
     * Some comment to make a space
     */
     1 + 1;
     // And after a working instruction, wreck havoc
     aCall()
}

/*
 * Main Script
 */
 anotherCall()
 